== {ProductName} personas

:description: Understand the primary user roles (Personas) within {ProductName} - Platform Engineers and Developers - and their typical interactions with the platform.

{ProductName} is an application development platform. Your usage of {ProductName} depends on your team role. {ProductName} users typically belong to one of two main categories:

* **Platform Engineers (PEs):** PEs enable application development for others, rather than engineering applications themselves. They typically own and manage the {ProductName} instance and its users.
* **Developers:** Developers engineer applications for their organization. They are primary {ProductName} users, utilizing the platform to build, test, and release their software.

Review the section below corresponding to your role for relevant information and links to further documentation.

=== Platform Engineers

First, you must link:https://github.com/konflux-ci/konflux-ci?tab=readme-ov-file#konflux-ci[install {ProductName}] before others can use it.

// TODO: Add xref for adding users and assigning them to workspaces
After installing {ProductName}, add users and assign them to {ProductName} workspaces. {ProductName} uses workspaces to manage role-based access control (RBAC).

=== Developers

{ProductName} helps you build, test, and release your applications. Understand these key {ProductName} definitions:
* An _Application_ consists of one or more components designed to run together.
* A _Component_ is a container image built from a source code repository.

To access {ProductName}, obtain the instance URL and your user credentials from your Platform Engineer. With access, you can perform various actions within {ProductName}, primarily focused on these three categories:

// TODO: Add xrefs for Build, Test, and Release actions
.   **Build:** Build your application's components into container images from source repositories. During the build process, {ProductName} runs quality and security checks against the source code and resulting images.
.   **Test:** Integrate components and test them together as a complete application within {ProductName} environments.
.   **Release:** Transfer your tested application artifacts from {ProductName} to an external destination, such as a container registry or deployment environment.