name: Linters
on:
  pull_request:
  merge_group:
    types: [checks_requested]
jobs:
  vale:
    name: vale
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to get file changes
      
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.adoc
      
      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          vale_flags: "--no-exit --output=line"
          fail_on_error: true
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}