name: Linters
on:
  pull_request:
  merge_group:
    types: [checks_requested]
jobs:
  vale:
    name: vale
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor
      
      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        with:
          vale_flags: "--no-exit --output=line"
          fail_on_error: true
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}